# Homepage Config
isSinglePage = true

# Meta Config
description = "Respondiendo a preguntas sobre el futuro de la administraci√≥n, CPS, marketing y empresa"

# Header Configuration
avatar = "img/foto-perfil.jpg"

#favicon
favicon = "icons/favicon copy.ico"

# disqus is a comment system. see https://disqus.com
disqusShortname = ""

[emoji]
enableEmoji = true

# giscus is a comment system based on GitHub Discussions. see https://giscus.app
[giscus]
    enable = false
    repo = ""
    repoId = ""
    category = "Announcements"
    categoryId = ""
    # mapping = "pathname"  # comment value is the default value
    # strict = 0
    # reactionsEnabled = 1
    # emitMetadata = 0
    # inputPosition = "top"
    # theme = "light"
    # lang = "zh-CN"
    # lazyLoading = true
